# Generated by Django 6.0 on 2025-12-10 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taxi", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="model",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="manufacturer",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
